### ISSUE TITLE
Use actions/setup-java@v4 to prevent warning

### ISSUE THREAD

**Issue by victortrusov** [simplelocalize/github-action-cli#2]
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/setup-java@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Switching to `actions/setup-java@v4` will fix it

**Comment by jpomykala** [comment]
Thanks! Switched to setup-java@v4: https://github.com/simplelocalize/github-action-cli/releases/tag/v3
